version: '3.8'

services:
  web:
    image: sirin-todolist-project
    container_name: todolist-container
    env_file: .env
    ports:
      - "9101:9101"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.30
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: