version: '3.8'

services:
  web:
    image: sirin-todolist-project
    container_name: todolist-container
    env_file: .env
    ports:
      - "9101:9101"
    restart: always
    networks:
      - back-tier

networks:
  back-tier:
    external: true