version: '3'
services:
  mysql:
    image: 'mysql:8.0.30'
    container_name: mysql-container
    environment:
      - 'MYSQL_DATABASE=${DATABASE_NAME}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER={MYSQL_USER}'
    ports:
      - '3306:3306'

