services:
  mysql:
    image: 'mysql:8.0.30'
    container_name: todolist-container
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'

    volumes:
      - ./db/mysql/data:/var/lib/mysql
