spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      platform: mysql
      mode: always

  profiles:
    include: oauth
