spring:

  h2:
    console:
      enabled: false
      path: /console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      platform: mysql
      mode: always

  profiles:
    include: oauth